import Head from "next/head";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <section className="bg-mainBG w-full flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <main></main>
    </section>
  );
}
